esphome:
  name: heatingpump
  friendly_name: ESP32-C6 THZ-504
  platformio_options:
    build_flags:
      - "-std=gnu++2a"
    build_unflags:
      - "-std=gnu++11"
      - "-fno-rtti"
  on_boot:
    priority: -100
    then:
      # Boot indication - Blue
      - light.turn_on:
          id: status_rgb_led
          brightness: 50%
          red: 0%
          green: 0%
          blue: 100%
      - delay: 3s

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

web_server:
  port: 80

# Debug and monitoring components
debug:
  update_interval: 30s

# RGB Status LED - Simple status indicator
light:
  - platform: esp32_rmt_led_strip
    pin: GPIO8
    num_leds: 1
    id: status_rgb_led
    name: "Status LED"
    chipset: WS2812
    rgb_order: RGB
# System monitoring sensors
sensor:
  - platform: uptime
    name: "ESP32-C6 Uptime"
    id: uptime_sensor
    update_interval: 60s
    
  - platform: wifi_signal
    name: "ESP32-C6 WiFi Signal"
    update_interval: 60s
    
  - platform: internal_temperature
    name: "ESP32-C6 Internal Temperature"
    update_interval: 60s

# Memory and system info
text_sensor:
#  - platform: debug
#    device:
#      name: "ESP32-C6 Device Info"
#    reset_reason:
#      name: "ESP32-C6 Reset Reason"
      
  - platform: wifi_info
    ip_address:
      name: "ESP32-C6 IP Address"
    ssid:
      name: "ESP32-C6 Connected SSID"
    mac_address:
      name: "ESP32-C6 Mac Address"
      
  - platform: version
    name: "ESP32-C6 ESPHome Version"

# Substitutions are now inherited from common.yaml

# Time configuration is inherited from common.yaml

#########################################
#                                       #
#   CAN configuration inherited from    #
#   common.yaml with ESP32-C6 pins      #
#                                       #
#########################################

#########################################
#                                       #
#   Buttons                             #
#                                       #
#########################################
button:
  - platform: restart
    name: "Restart ESP32-C6 THZ-504"

#########################################
#                                       #
#   WiFi Configuration                  #
#                                       #
#########################################
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # ESP32-C6 specific settings
  enable_on_boot: true
  power_save_mode: none
  
  # Static IP configuration  
  manual_ip:
    static_ip: 192.168.200.80
    gateway: 192.168.200.1
    subnet: 255.255.255.0
    dns1: 192.168.200.1
    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heatingpump Fallback Hotspot"
    password: "configesp32"

captive_portal:



# Safe mode for emergency access
safe_mode:
  disabled: false
  reboot_timeout: 10min
  num_attempts: 5

#########################################
#                                       #
#   Packages                            #
#                                       #
#########################################
packages:
  thz504: !include yaml/thz504.yaml



# CAN Bus Configuration is now inherited from common.yaml
# Status LED Automation - Visual system status
interval:
  - interval: 3s
    then:
      - if:
          condition:
            wifi.connected:
          then:
            # WiFi connected - Solid Green (ready for CAN bus)
            - light.turn_on:
                id: status_rgb_led
                brightness: 30%
                red: 0%
                green: 100%
                blue: 0%
          else:
            # WiFi disconnected - Solid Red
            - light.turn_on:
                id: status_rgb_led
                brightness: 30%
                red: 100%
                green: 0%
                blue: 0%
