esphome:
  name: heatingpump
  friendly_name: ESP32-C6 Minimal Test
  on_boot:
    priority: -100
    then:
      # Boot indication - Blue
      - light.turn_on:
          id: status_rgb_led
          brightness: 50%
          red: 0%
          green: 0%
          blue: 100%
      - delay: 3s

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

# Web server
web_server:
  port: 80
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heatingpump Fallback"
    password: "configesp32"

captive_portal:


# RGB Status LED - Simple status indicator
light:
  - platform: esp32_rmt_led_strip
    pin: GPIO8
    num_leds: 1
    id: status_rgb_led
    name: "Status LED"
    chipset: WS2812
    rgb_order: RGB


# Basic sensors for monitoring
sensor:
  - platform: uptime
    name: "Uptime"
    update_interval: 60s
    
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

# System info
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
    mac_address:
      name: "MAC Address"
      
  - platform: version
    name: "ESPHome Version"

# Restart button
button:
  - platform: restart
    name: "Restart"
# WiFi Configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
# Status LED Automation - Visual system status
interval:
  - interval: 3s
    then:
      - if:
          condition:
            wifi.connected:
          then:
            # WiFi connected - Solid Green
            - light.turn_on:
                id: status_rgb_led
                brightness: 30%
                red: 0%
                green: 100%
                blue: 0%
          else:
            # WiFi disconnected - Solid Red
            - light.turn_on:
                id: status_rgb_led
                brightness: 30%
                red: 100%
                green: 0%
                blue: 0%

# Boot sequence is now in esphome: section above

