esphome:
  name: esp32-c6-thz504
  friendly_name: ESP32-C6 THZ-504
  platformio_options:
    build_flags:
      - "-std=gnu++2a"
    build_unflags:
      - "-std=gnu++11"
      - "-fno-rtti"

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO
  baud_rate: 0
  hardware_uart: UART1

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

substitutions:
  interval_very_fast: 15s
  interval_fast: 30s
  interval_medium: 60s
  interval_slow: 5min
  interval_very_slow: 15min
  interval_once_in_a_while: 1h

  entity_room_temperature: "sensor.durchschnittstemperatur_haus_ohne_keller"
  entity_humidity: "sensor.durchschnitt_luftfeuchtigkeit_haus"

#########################################
#                                       #
#   CAN configuration inherited from    #
#   common.yaml with ESP32-C6 pins      #
#                                       #
#########################################

#########################################
#                                       #
#   Buttons                             #
#                                       #
#########################################
button:
  - platform: restart
    name: "Restart ESP32-C6 THZ-504"

#########################################
#                                       #
#   WiFi Configuration                  #
#                                       #
#########################################
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP32-C6-THZ504 Fallback Hotspot"
    password: "configesp32"

captive_portal:

#########################################
#                                       #
#   Packages                            #
#                                       #
#########################################
packages:
# energymeter: !include yaml/energymeter.yaml
# evu: !include yaml/evu.yaml
# watermeter: !include yaml/watermeter.yaml
# sensors: !include yaml/sensors.yaml
# thz404: !include yaml/thz404.yaml
  thz504: !include yaml/thz504.yaml
# thz55eco: !include yaml/thz5_5_eco.yaml
# ttf07: !include yaml/ttf07.yaml
# wpl13: !include yaml/wpl13.yaml
# kondensatpumpe: !include yaml/kondensatpumpe.yaml
