sensor:
  - platform: template
    name: "${property}"
    id: ${property}
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    icon: "mdi:thermometer"
    update_interval: ${update_interval:$interval_fast}
    lambda: |-
      return {};  // Updated via CAN bus callbacks

number:
  - platform: template
    name: "${property} Setpoint"
    id: ${property}_setpoint
    unit_of_measurement: "°C"
    min_value: 5.0
    max_value: 75.0
    step: 0.5
    mode: box
    optimistic: true
    set_action:
      then:
        - lambda: |-
            const auto value = static_cast<std::uint16_t>(x * 10.0f);
            sendData(${target:Kessel}, Property::k${property}, value);